
insert into `users` ( `lastAt`, `password`, `isLock`, `id`, `openid`, `avatar`, `roleType`, `username`, `unionid`, `createdAt`, `updatedAt`) values ( '2016-08-11 22:32:22', '$2a$10$qfWySewFK6j/Oqrbjmzp0Olq4UMcld8MroxxsYK6Wg3jqQTrPbB0e', '0', '1', null, '', '0', 'admin', null, '2016-08-11 22:32:25', '2016-08-11 22:32:28');


insert into `areas` ( `id`, `title`, `parentId`, `index`) values ( '1', 'Hong Kong', '0', '0');
insert into `areas` ( `id`, `title`, `parentId`, `index`) values ( '2', 'Shenzhen', '0', '0');
insert into `areas` ( `id`, `title`, `parentId`, `index`) values ( '3', 'Beijing', '0', '0');
insert into `areas` ( `id`, `title`, `parentId`, `index`) values ( '4', 'Shanghai', '0', '0');
insert into `areas` ( `id`, `title`, `parentId`, `index`) values ( '5', 'Chengdu', '0', '0');
insert into `areas` ( `id`, `title`, `parentId`, `index`) values ( '6', 'Qingdao', '0', '0');
insert into `areas` ( `id`, `title`, `parentId`, `index`) values ( '7', 'Hangzhou', '0', '0');
insert into `areas` ( `id`, `title`, `parentId`, `index`) values ( '8', 'Guangzhou', '0', '0');
insert into `areas` ( `id`, `title`, `parentId`, `index`) values ( '9', 'Nanjing', '0', '0');
insert into `areas` ( `id`, `title`, `parentId`, `index`) values ( '10', 'Xi\'An', '0', '0');
insert into `areas` ( `id`, `title`, `parentId`, `index`) values ( '11', 'Lanzhou', '0', '0');
insert into `areas` ( `id`, `title`, `parentId`, `index`) values ( '12', 'Haikou', '0', '0');
insert into `areas` ( `id`, `title`, `parentId`, `index`) values ( '13', 'Tianjin', '0', '0');
insert into `areas` ( `id`, `title`, `parentId`, `index`) values ( '14', 'Kunming', '0', '0');
insert into `areas` ( `id`, `title`, `parentId`, `index`) values ( '15', 'Taiwan', '0', '0');
insert into `areas` ( `id`, `title`, `parentId`, `index`) values ( '16', 'Chongqing', '0', '0');
insert into `areas` ( `id`, `title`, `parentId`, `index`) values ( '17', 'Wuhan', '0', '0');
insert into `areas` ( `id`, `title`, `parentId`, `index`) values ( '18', 'Shenyang', '0', '0');
insert into `areas` ( `id`, `title`, `parentId`, `index`) values ( '19', 'Changchun', '0', '0');
insert into `areas` ( `id`, `title`, `parentId`, `index`) values ( '20', 'Suzhou', '0', '0');
insert into `areas` ( `id`, `title`, `parentId`, `index`) values ( '21', 'Changsha', '0', '0');
insert into `areas` ( `id`, `title`, `parentId`, `index`) values ( '22', 'Dongguan', '0', '0');
insert into `areas` ( `id`, `title`, `parentId`, `index`) values ( '23', 'WuXi', '0', '0');
insert into `areas` ( `id`, `title`, `parentId`, `index`) values ( '24', 'Ningbo', '0', '0');
insert into `areas` ( `id`, `title`, `parentId`, `index`) values ( '25', 'Changzhou', '0', '0');
insert into `areas` ( `id`, `title`, `parentId`, `index`) values ( '26', 'Dalian', '0', '0');
insert into `areas` ( `id`, `title`, `parentId`, `index`) values ( '27', 'Guiyang', '0', '0');
insert into `areas` ( `id`, `title`, `parentId`, `index`) values ( '28', 'Zhuhai', '0', '0');
insert into `areas` ( `id`, `title`, `parentId`, `index`) values ( '29', 'Others', '0', '1');




insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '1', 'Angola', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '2', 'Albania', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '3', 'Algeria', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '4', 'Andorra', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '5', 'Anguilla', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '6', 'Antigua and Barbuda', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '7', 'Argentina', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '8', 'Armenia', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '9', 'Ascension', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '10', 'Australia', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '11', 'Austria', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '12', 'Azerbaijan', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '13', 'Bahamas', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '14', 'Bahrain', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '15', 'Bangladesh', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '16', 'Barbados', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '17', 'Belarus', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '18', 'Belgium', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '19', 'Belize', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '20', 'Benin', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '21', 'Bermuda Is.', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '22', 'Bolivia', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '23', 'Botswana', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '24', 'Brazil', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '25', 'Brunei', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '26', 'Bulgaria', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '27', 'Burkina-faso', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '28', 'Burma', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '29', 'Burundi', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '30', 'Cameroon', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '31', 'Canada', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '32', 'Cayman Is.', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '33', 'Central African Republic', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '34', 'Chad', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '35', 'Chile', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '36', 'China', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '37', 'Colombia', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '38', 'Congo', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '39', 'Cook Is.', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '40', 'Costa Rica', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '41', 'Cuba', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '42', 'Cyprus', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '43', 'Czech Republic', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '44', 'Denmark', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '45', 'Djibouti', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '46', 'Dominica Rep.', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '47', 'Ecuador', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '48', 'Egypt', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '49', 'EI Salvador', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '50', 'Estonia', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '51', 'Ethiopia', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '52', 'Fiji', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '53', 'Finland', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '54', 'France', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '55', 'French Guiana', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '56', 'Gabon', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '57', 'Gambia', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '58', 'Georgia', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '59', 'Germany', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '60', 'Ghana', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '61', 'Gibraltar', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '62', 'Greece', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '63', 'Grenada', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '64', 'Guam', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '65', 'Guatemala', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '66', 'Guinea', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '67', 'Guyana', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '68', 'Haiti', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '69', 'Honduras', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '70', 'Hongkong', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '71', 'Hungary', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '72', 'Iceland', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '73', 'India', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '74', 'Indonesia', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '75', 'Iran', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '76', 'Iraq', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '77', 'Ireland', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '78', 'Israel', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '79', 'Italy', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '80', 'Ivory Coast', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '81', 'Jamaica', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '82', 'Japan', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '83', 'Jordan', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '84', 'Kampuchea (Cambodia )', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '85', 'Kazakstan', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '86', 'Kenya', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '87', 'Korea', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '88', 'Kuwait', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '89', 'Kyrgyzstan', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '90', 'Laos', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '91', 'Latvia', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '92', 'Lebanon', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '93', 'Lesotho', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '94', 'Liberia', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '95', 'Libya', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '96', 'Liechtenstein', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '97', 'Lithuania', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '98', 'Luxembourg', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '99', 'Macao', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '100', 'Madagascar', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '101', 'Malawi', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '102', 'Malaysia', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '103', 'Maldives', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '104', 'Mali', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '105', 'Malta', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '106', 'Mariana Is', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '107', 'Martinique', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '108', 'Mauritius', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '109', 'Mexico', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '110', 'Moldova, Republic of', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '111', 'Monaco', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '112', 'Mongolia', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '113', 'Montserrat Is', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '114', 'Morocco', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '115', 'Mozambique', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '116', 'Namibia', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '117', 'Nauru', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '118', 'Nepal', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '119', 'Netheriands Antilles', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '120', 'Netherlands', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '121', 'New Zealand', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '122', 'Nicaragua', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '123', 'Niger', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '124', 'Nigeria', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '125', 'North Korea', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '126', 'Norway', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '127', 'Oman', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '128', 'Pakistan', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '129', 'Panama', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '130', 'Papua New Cuinea', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '131', 'Paraguay', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '132', 'Peru', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '133', 'Philippines', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '134', 'Poland', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '135', 'French Polynesia', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '136', 'Portugal', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '137', 'Puerto Rico', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '138', 'Qatar', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '139', 'Reunion', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '140', 'Romania', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '141', 'Russia', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '142', 'Saint Lueia', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '143', 'Saint Vincent', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '144', 'Samoa Eastern', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '145', 'Samoa Western', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '146', 'San Marino', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '147', 'Sao Tome and Principe', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '148', 'Saudi Arabia', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '149', 'Senegal', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '150', 'Seychelles', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '151', 'Sierra Leone', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '152', 'Singapore', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '153', 'Slovakia', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '154', 'Slovenia', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '155', 'Solomon Is', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '156', 'Somali', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '157', 'South Africa', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '158', 'Spain', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '159', 'Sri Lanka', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '160', 'St.Lucia', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '161', 'St.Vincent', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '162', 'Sudan', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '163', 'Suriname', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '164', 'Swaziland', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '165', 'Sweden', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '166', 'Switzerland', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '167', 'Syria', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '168', 'Taiwan', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '169', 'Tajikstan', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '170', 'Tanzania', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '171', 'Thailand', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '172', 'Togo', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '173', 'Tonga', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '174', 'Trinidad and Tobago', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '175', 'Tunisia', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '176', 'Turkey', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '177', 'Turkmenistan', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '178', 'Uganda', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '179', 'Ukraine', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '180', 'United Arab Emirates', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '181', 'United Kingdom', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '182', 'United States of America', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '183', 'Uruguay', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '184', 'Uzbekistan', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '185', 'Venezuela', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '186', 'Vietnam', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '187', 'Yemen', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '188', 'Yugoslavia', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '189', 'Zimbabwe', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '190', 'Zaire', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '191', 'Zambia', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '192', 'Croatia', '0', '0');
insert into `nationalities` ( `id`, `title`, `parentId`, `index`) values ( '193', 'Others', '0', '1');